title: Sdl-community
description: This repository will contain all applications and plugins developed and published under SDL Community
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
